#!/bin/bash
# End-to-end packaging rehearsal on a real Omarchy machine (QEMU VM is ideal).
#
# This is what "Install > Gaming > Quake" will do, except extra is not
# published yet so we `makepkg` + `pacman -U` instead of `omarchy-pkg-add`.
#
# Fresh Omarchy 4 VM:
#   1. Finish the ISO install and log into the graphical session.
#      Plugin enable talks to omarchy-shell — a SSH-only login is not enough.
#   2. git clone https://github.com/ryrobes/omarchy-quake.git
#   3. cd omarchy-quake && ./scripts/test-packaged-install.sh
#
# Options:
#   --no-launch   stop after plugin enable (do not gtk-launch)
#   --skip-build  reuse an existing .pkg.tar.zst in build/makepkg-omarchy-quake/
#
# First Play downloads shareware (~18MB). QEMU without a GPU uses lavapipe.

set -euo pipefail

ROOT=$(cd "$(dirname "$0")/.." && pwd)
cd "$ROOT"

LAUNCH=1
SKIP_BUILD=0
for arg in "$@"; do
  case $arg in
    --no-launch) LAUNCH=0 ;;
    --skip-build) SKIP_BUILD=1 ;;
    -h | --help)
      sed -n '2,20p' "$0"
      exit 0
      ;;
    *)
      echo "unknown option: $arg" >&2
      exit 1
      ;;
  esac
done

step() { printf '\n\033[1m==> %s\033[0m\n' "$*"; }
run() {
  printf '+ %s\n' "$*"
  "$@"
}

pkg_add() {
  if command -v omarchy-pkg-add >/dev/null; then
    run omarchy-pkg-add "$@"
  else
    run sudo pacman -S --noconfirm --needed "$@"
  fi
}

if (( EUID == 0 )); then
  echo "do not run as root — makepkg refuses that. sudo is used only for pacman." >&2
  exit 1
fi

if [[ -z ${WAYLAND_DISPLAY:-} && -z ${DISPLAY:-} ]]; then
  echo "no graphical session (WAYLAND_DISPLAY/DISPLAY empty)." >&2
  echo "log into Omarchy on the VM console, open a terminal there, and re-run." >&2
  exit 1
fi

PKGVER=$(awk -F= '/^pkgver=/{gsub(/"/, "", $2); print $2; exit}' "$ROOT/packaging/PKGBUILD")
PKGREL=$(awk -F= '/^pkgrel=/{gsub(/"/, "", $2); print $2; exit}' "$ROOT/packaging/PKGBUILD")
WORKDIR=$ROOT/build/makepkg-omarchy-quake
ARCH=$(uname -m)

step "0. build dependencies (compiler + lavapipe for VMs without a GPU)"
# Filter through `pacman -T` first: it resolves provides, so an installed
# vulkan-headers-git (etc.) satisfies vulkan-headers instead of making
# `pacman -S` fail on a package conflict.
DEPS=(
  base-devel git meson ninja pkgconf patch
  sdl3 vulkan-headers vulkan-icd-loader vulkan-swrast glslang spirv-tools
  mpg123 libvorbis flac opus libogg
  python
)
mapfile -t MISSING < <(pacman -T "${DEPS[@]}" || true)
if (( ${#MISSING[@]} )); then
  pkg_add "${MISSING[@]}"
else
  echo "all build dependencies already installed"
fi

step "1. unit tests (no vkQuake compile)"
run make test

step "2. DESTDIR layout (fake engine — same checks as tests/test-install-layout.sh)"
run bash "$ROOT/tests/test-install-layout.sh"

if (( SKIP_BUILD )); then
  step "3. skip makepkg (--skip-build)"
else
  step "3. makepkg from this checkout (not the GitHub tag — so the clone is what you get)"
  run rm -rf "$WORKDIR"
  run mkdir -p "$WORKDIR"
  run tar --exclude=./build --exclude=./vendor/vkQuake --exclude=./.git \
    --exclude=./.cache --exclude=./__pycache__ \
    --transform "s,^\./,omarchy-quake-${PKGVER}/," \
    -czf "$WORKDIR/omarchy-quake-${PKGVER}.tar.gz" .
  cat >"$WORKDIR/PKGBUILD" <<EOF
# Generated by scripts/test-packaged-install.sh from packaging/PKGBUILD
pkgname=omarchy-quake
pkgver=${PKGVER}
pkgrel=${PKGREL}
pkgdesc="Quake 1 for Omarchy (vkQuake, shareware fetch, Tailscale deathmatch)"
arch=('x86_64' 'aarch64')
url="https://github.com/ryrobes/omarchy-quake"
license=('MIT' 'GPL-2.0-or-later')
options=('!debug')
depends=(sdl3 vulkan-icd-loader mpg123 libvorbis flac opus libogg libarchive wl-clipboard hicolor-icon-theme python)
makedepends=(meson ninja git patch pkgconf vulkan-headers glslang spirv-tools)
source=(
  "omarchy-quake-${PKGVER}.tar.gz"
  "vkQuake-1.35.0.tar.gz::https://github.com/Novum/vkQuake/archive/refs/tags/1.35.0.tar.gz"
)
sha256sums=(
  'SKIP'
  '9f3a2bbf7ef22224c26a1a0d574562573fdaae2dc9758a98068617062d49c584'
)
prepare() {
  rm -rf "\$srcdir/\$pkgname-\$pkgver/vendor/vkQuake"
  cp -a "\$srcdir/vkQuake-1.35.0" "\$srcdir/\$pkgname-\$pkgver/vendor/vkQuake"
}
build() {
  cd "\$srcdir/\$pkgname-\$pkgver"
  bash scripts/build-engine.sh
}
package() {
  cd "\$srcdir/\$pkgname-\$pkgver"
  DESTDIR="\$pkgdir" PREFIX=/usr SKIP_BUILD=1 bash scripts/install.sh
}
EOF
  printf '+ (cd %s && makepkg -f -s --noconfirm)\n' "$WORKDIR"
  (cd "$WORKDIR" && makepkg -f -s --noconfirm)
fi

PKG=$(ls -1 "$WORKDIR"/omarchy-quake-"${PKGVER}"-"${PKGREL}"-"${ARCH}".pkg.tar.zst 2>/dev/null | head -n1 || true)
if [[ -z $PKG ]]; then
  PKG=$(ls -1 "$WORKDIR"/omarchy-quake-*.pkg.tar.zst 2>/dev/null | head -n1 || true)
fi
[[ -n $PKG && -f $PKG ]] || {
  echo "no package in $WORKDIR — makepkg failed?" >&2
  exit 1
}
echo "package: $PKG"

step "4. install the package (stand-in for: omarchy-pkg-add omarchy-quake)"
echo "+ # future installer: omarchy-pkg-add omarchy-quake"
run sudo pacman -U --noconfirm "$PKG"
run pacman -Q omarchy-quake
run command -v omarchy-quake
run test -x /usr/lib/omarchy-quake/vkquake
run test -f /usr/share/omarchy-quake/plugin/Panel.qml
run test -f /usr/share/applications/org.omarchy.quake.desktop
run grep -qx 'Exec=omarchy-quake panel' /usr/share/applications/org.omarchy.quake.desktop

step "5. user integration (same commands as packaging/omarchy-install-gaming-quake.example.sh)"
run rm -f "$HOME/.local/bin/quake-omarchy"
# Do not delete ~/.local/bin/omarchy-quake here unless it exists from an old
# make install — pacman owns /usr/bin/omarchy-quake.
if [[ -e $HOME/.local/bin/omarchy-quake ]]; then
  run rm -f "$HOME/.local/bin/omarchy-quake"
fi

plugin_src=/usr/share/omarchy-quake/plugin
plugin_dest="$HOME/.config/omarchy/plugins/quake.omarchy"
[[ -d $plugin_src ]] || {
  echo "omarchy-quake did not ship $plugin_src" >&2
  exit 1
}
run mkdir -p "$plugin_dest"
# Copy, do not symlink: omarchy-plugin-validate rejects any symlink in a plugin folder.
run find "$plugin_dest" -mindepth 1 -delete
run cp -f "$plugin_src/"* "$plugin_dest/"
run touch "$plugin_dest"/*.qml "$plugin_dest"/*.js "$plugin_dest"/manifest.json
if command -v omarchy-plugin-validate >/dev/null; then
  run omarchy-plugin-validate "$plugin_dest"
fi
# The shell notices the new plugin dir via inotify and rescans asynchronously,
# so an immediate enable can race it ("plugin is not known"). Rescan, then retry.
run omarchy-shell shell rescanPlugins >/dev/null 2>&1 || true
enabled=0
for _ in 1 2 3 4 5 6 7 8 9 10; do
  if omarchy-plugin-enable quake.omarchy >/dev/null 2>&1; then
    enabled=1
    break
  fi
  sleep 0.3
done
if (( ! enabled )); then
  run omarchy-plugin-enable quake.omarchy
fi

hypr_src=/usr/share/omarchy-quake/hypr/quake.lua
hypr_dest="$HOME/.config/hypr/apps/quake-omarchy.lua"
if [[ -f $hypr_src ]]; then
  run mkdir -p "$(dirname "$hypr_dest")"
  run install -m 0644 "$hypr_src" "$hypr_dest"
fi
HYPR_LUA=$HOME/.config/hypr/hyprland.lua
if [[ -f $HYPR_LUA ]] && ! grep -q 'hypr.apps.quake-omarchy' "$HYPR_LUA"; then
  echo "+ wire require(\"hypr.apps.quake-omarchy\") into ~/.config/hypr/hyprland.lua"
  cp "$HYPR_LUA" "$HYPR_LUA.bak.$(date +%s)"
  python3 - "$HYPR_LUA" <<'PY'
from pathlib import Path
import sys
path = Path(sys.argv[1])
text = path.read_text()
line = 'require("hypr.apps.quake-omarchy")\n'
if "hypr.apps.quake-omarchy" in text:
    raise SystemExit(0)
for needle in ('require("hypr.apps.synchro")\n', 'require("hypr.autostart")\n'):
    if needle in text:
        path.write_text(text.replace(needle, needle + line, 1))
        raise SystemExit(0)
path.write_text(text + "\n" + line)
PY
fi

if command -v omarchy >/dev/null; then
  run omarchy restart shell || true
fi
if command -v hyprctl >/dev/null; then
  run hyprctl reload || true
fi

step "6. sanity from PATH (the packaged binary, not ~/.local)"
run type -a omarchy-quake
run omarchy-quake --help >/dev/null
run omarchy-quake source || true

if (( LAUNCH )); then
  step "7. launch (same as the installer: gtk-launch org.omarchy.quake)"
  echo "First Play downloads shareware (~18MB) if you have no PAKs."
  printf '+ setsid uwsm-app -- gtk-launch org.omarchy.quake >/dev/null 2>&1 &\n'
  setsid uwsm-app -- gtk-launch org.omarchy.quake >/dev/null 2>&1 &
else
  step "7. skip launch (--no-launch)"
  echo "When ready:  omarchy-quake panel"
  echo "         or:  gtk-launch org.omarchy.quake"
fi

printf '\n\033[1mPackaged install looks good.\033[0m\n'
echo "Play:            omarchy-quake"
echo "Panel:           omarchy-quake panel   (or Super+Space, type Quake)"
echo "Host:            omarchy-quake host --map e1m2"
echo "Remove later:    sudo pacman -Rns omarchy-quake"
echo "                 rm -rf ~/.config/omarchy/plugins/quake.omarchy"
echo "Uninstall saves: rm -rf ~/.config/quake-omarchy ~/.local/share/quake-omarchy"
